baseurl = "https://jsybrandt.github.io"
languageCode = "en-us"
title = "Justin Sybrandt"
theme = "cactus"
copyright = "Justin Sybrandt"
disqusShortname = "sybrandt-com"

[params]
colortheme = "dark"
description = """
Here I post updates on projects, opine on the state of tech, and dive into
recent advancements in Machine Learning.

I currently work at Google Deepmind where I work on
building machine learning systems that intend to dramatically simplify the
overhead of deploying production machine learning systems.

Before that, I completed my Ph.D. at Clemson University. My dissertation
focused on automatic biomedical hypothesis generation. Over the course of many
projects I applied graph mining and natural language processing to anticipate
recent advances in medical research.
"""
mainSectionTitle = "Recent Updates"
mathjax = true
logo = "img/icon.png"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 3

[[menu.main]]
name = "Resume"
weight = 4
url = "/documents/cv.pdf"


[[params.social]]
name = "email"
link = "justin@sybrandt.com"

[[params.social]]
name = "mastodon"
link = "https://techhub.social/@jsybrandt"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/justin-sybrandt-ph-d-616b9148/"

[[params.social]]
name = "github"
link = "https://github.com/JSybrandt"

[[params.social]]
name = "scholar"
link = "https://scholar.google.com/citations?user=X7tyILEAAAAJ"


# Default markdown highlighting.
[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
